# open docker desktop
# cd to root of project
# docker compose up -d
version: "3.9"

services:
  database:
    image: postgres:15.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'docker-username'
      POSTGRES_PASSWORD: 'docker-password'
      POSTGRES_DB: 'docker-database'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'